<?php
require 'fpdf/fpdf.php';
include 'core/initForMainLogPage.php';
?>

<?php
 if(logged_in()){
$data=user_dataEmp('username');
$usernameData=$data['username'];
$data=user_dataEmp('empId');
$empId=$data['empId'];
 }else{
	 header('Location: index.php');
 }
?>
<?php include 'includes/adminHeadAll.php';?>

<header>
 <?php include 'includes/employeeMenu.php';?>  
  </header>
  <div class="container">
<br/>
    <h3>My Salary Report</h3>
  
     <?php  
	
	 	
		$pdf= new FPDF();
		
		$pdf->AddPage();
		
	 //HEADER infromation of employee:
		$date=date("jS F Y, g:i:s a");
		$pdf->SetFont("Arial","B",8);
		$pdf->Cell(0,8,"Employee Salary Reports",1,1,"C");
		$pdf->Cell(0,8,"Generated by Employee",0,1,"L");
		$pdf->Cell(0,8,"Date : $date",0,1,"L");
		$pdf->Ln(4);
		$pdf->SetFont("Arial","B",8);
		$pdf->SetFillColor(102,102,102);
    	$pdf->SetTextColor(255,255,255);
		$pdf->SetDrawColor(31, 152, 152); 
		$pdf->SetAutoPageBreak(true, 10);
		//  ability to display page numbers on your PDF pages.
		$pdf->AliasNbPages();
		$pdf->Cell(20,8,"Payslip ID",1,0,"C",TRUE);
		$pdf->Cell(30,8,"Emp.Name",1,0,"C",TRUE);
		$pdf->Cell(20,8,"Generated On",1,0,"C",TRUE);
		$pdf->Cell(20,8,"Basic Salary",1,0,"C",TRUE);
		$pdf->Cell(20,8,"No. Of Absent",1,0,"C",TRUE);
		$pdf->Cell(25,8,"Salary Per Day",1,0,"C",TRUE);
		$pdf->Cell(35,8,"Deduction Of Absentee",1,0,"C",TRUE);
		$pdf->Cell(20,8,"Net Salary",1,0,"C",TRUE);
		$pdf->Ln(8);
		$pdf->SetFont("Arial","B",8);
		$pdf->SetTextColor(0, 0, 0);
		
			//querying employee data into table
	$query=mysql_query("SELECT payrollId,payroll.empId,name,date,basicSalary,numOfLeaves,salaryPerDay,deduction,netSalary 
						FROM payroll JOIN emplog ON emplog.empId='".$_SESSION['empId']."' WHERE  payroll.empId=emplog.empId ");

			$label=0;
		$netTotal=0;
		$net=0;
	while($row=mysql_fetch_array($query)){
		
		$pdf->Cell(20,8,$row['payrollId'],1,0,"L"); 
		$pdf->Cell(30,8,$row['name'],1,0,"L"); 
		$pdf->Cell(20,8,$row['date'],1,0,"L"); 
		$pdf->Cell(20,8,$row['basicSalary'],1,0,"L"); 
		$pdf->Cell(20,8,$row['numOfLeaves'],1,0,"L"); 
		$pdf->Cell(25,8,$row['salaryPerDay'],1,0,"L"); 
		$pdf->Cell(35,8,$row['deduction'],1,0,"L"); 
		$pdf->Cell(20,8,$row['netSalary'],1,0,"L"); 
		$pdf->Ln(8);
		
		$netTotal=$netTotal+$row['netSalary'];
		
		}
	$pdf->SetFont("Arial","B",8);
	$pdf->Cell(140,8,"",0);
	$pdf->SetFont("Arial","B",8);
		$pdf->SetFillColor(102,102,102);
    	$pdf->SetTextColor(255,255,255);
		$pdf->SetDrawColor(31, 152, 152); 
	$pdf->Cell(50,8,"Net Income:  ".$netTotal,1,0,"C",TRUE);
	
	ob_end_clean();
	$pdf->Output("employee-salary-report","D");
	?>
     
	

 <p>All your salary details can be found here and you can print it.</p>
 </div> 
	 <?php include 'includes/footerAll.php';?>  
</body>
</html>
